title: GDSTEM
description: Global Dynamical and Structural Terrestrial Ecosystem Model

theme: minima

header_pages:
  - index.md
  - news.md
  - model.md
  - team.md
  - publications.md
  - legacy.md

plugins:
  - jekyll-seo-tag

# Basic SEO info
title: "Global Dynamical and Structural Terrestrial Ecosystem Model (GDSTEM)"
description: "Official website for GDSTEM — a global cohort-based terrestrial ecosystem model for carbon, nitrogen, and water dynamics."
url: "https://ucdglobalchange.github.io/gdstem"   # your live site URL
