title: GDSTEM
description: Global Dynamical and Structural Terrestrial Ecosystem Model

theme: minima

header_pages:
  - index.md
  - model.md
  - team.md
  - publications.md
  - news.md
  - legacy.md
